name: daily-task


on:
  
  #push: # push触发
    #branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '21 0/2 * * *'
    

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    # 安装依赖
    - name: Install dependencies
      run: npm install
      
    - name: Set date time
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    
    - name: Set cache time
      id: cdate
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: restore task cache
      uses: actions/cache@v2
      id: use-task-cache
      with:
        path: |
          /home/runner/.AutoSignMachine
        key: ${{ runner.os }}-task-${{ steps.date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-task-${{ steps.cdate.outputs.date }}
          ${{ runner.os }}-
     
       
    
    # 运行 unicom 签到任务
    - name: Run unicom daily task
      env:
        user: ${{ secrets.unicom_user }}
        password: ${{ secrets.unicom_password }}
        appid: ${{ secrets.unicom_appid }}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid}  
     # run: node index.js unicom --user=${user} --password=${password} --appid=${appid}  --tryrun --tasks dailygameflow

