name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days: #要保留的天数
        description: 'Number of days.'
        required: true
        default: 2
      runs: #要为每个yml保留的个数
        description: 'Number of runs.'
        required: true
        default: 6

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.runs }}
